services:
  - type: web
    name: kazan-md-roi-original
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.1
      - key: OWNER_NUMBER
        value: "243981776812"
      - key: PREFIX
        value: "."
      - key: PHONE_NUMBER
        value: "243981776812"
      - key: SESSION_ID
        value: KAZAN-MD
      - key: PAIRING_CODE
        value: "true"
